name: Winlogbeat
pipeline:
  - name: json
    external:
      name: json.parse-json
      properties:
        output_field: event
  - name: fields
stages:
  fields:
    actions:
      - set:
          "@timestamp": '{{json.event["@timestamp"]}}'
          action: "{{json.event.action}}"
          action.properties: "{{json.event.winlog.event_data}}"
          user.target.name: "{{json.event.winlog.event_data.TargetUserName}}"
          user.target.domain: "{{json.event.winlog.event_data.TargetDomainName}}"
          action.id: "{{json.event.event.code | string}}"
          agent: "{{json.event.agent}}"
          as: "{{json_event.event.as}}"
          beat: "{{json.event.beat}}"
          client: "{{json_event.event.client}}"
          cloud: "{{json_event.event.cloud}}"
          cloud.image.id: "{{json_event.event.cloud.image.id}}"
          code_signature: "{{json_event.event.code_signature}}"
          container: "{{json_event.event.container}}"
          data_stream: "{{json_event.event.data_stream}}"
          destination: "{{json.event.destination}}"
          dll: "{{json.event.dll}}"
          dns: "{{json.event.dns}}"
          docker: "{{json_event.event.docker}}"
          error: "{{json.event.error}}"
          event.action: "{{json.event.event.action}}"
          event.category: "{{json.event.event.category}}"
          event.code: "{{json.event.event.code | string}}"
          event.kind: "{{json.event.event.kind}}"
          event.module: "{{json.event.event.module}}"
          event.reason: "{{json.event.event.reason}}"
          event.provider: "{{json.event.event.provider}}"
          event.type: "{{json.event.event.type}}"
          event.original: "{{json.event.message}}"
          action.outcome: "{{json.event.event.outcome}}"
          file: "{{json.event.file}}"
          jolokia: "{{json_event.event.jolokia}}"
          kubernetes: "{{json_event.event.kubernetes}}"
          host: "{{json.event.host}}"
          log: "{{json.event.log}}"
          network: "{{json.event.network}}"
          powershell: "{{json.event.powershell}}"
          process: "{{json.event.process}}"
          registry: "{{json.event.registry}}"
          source: "{{json.event.source}}"
          sysmon: "{{json.event.sysmon}}"
          timeseries: "{{json_event.event.timeseries}}"
          url: "{{json.event.url}}"
          user: "{{json.event.user}}"
          winlog: "{{json.event.winlog}}"
      - set:
          winlog.provider_guid: "{{json.event.winlog.provider_guid | lower}}"
        filter: '{{json.event.winlog.get("provider_guid") != None}}'
      - set:
          winlog.activity_id: "{{json.event.winlog.activity_id | lower}}"
        filter: '{{json.event.winlog.get("activity_id") != None}}'
