name: vade-cloud
pipeline:
  - name: parse_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: "message"

  - name: parse_timestamp
    external:
      name: date.parse
      properties:
        input_field: "{{parse_event.message.date}}"
        output_field: date

  - name: set_base_fields

stages:
  set_base_fields:
    actions:
      - set:
          "@timestamp": "{{ parse_timestamp.date }}"

      - set:
          event.kind: "event"
          event.category: ["email"]
          event.type: ["info"]

      - set:
          email.from.address: ["{{ parse_event.message.from }}"]
          email.to.address: ["{{ parse_event.message.to }}"]
          email.subject: "{{ parse_event.message.subject }}"
          email.local_id: "{{ parse_event.message.messageId }}"
          destination.domain: "{{ parse_event.message.domain }}"
          destination.ip: "{{ parse_event.message.ip }}"

          event.reason: "{{ parse_event.message.filterReason }}"
          event.action: "{{ parse_event.message.operationType }}"

      - set:
          vadecloud.filter_type: "{{ parse_event.message.filterType }}"
          vadecloud.sandboxed: "{{ parse_event.message.sandboxed }}"
          vadecloud.site: "{{ parse_event.message.site }}"
          vadecloud.spam_level: "{{ parse_event.message.spamLevel }}"
          vadecloud.tag: "{{ parse_event.message.tag }}"
